# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix: ⬆️ "
    reviewers: ["zoido"]
    open-pull-requests-limit: 0 # Only automate security updates for go.mod.    

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci: ⬆️ "
    reviewers: ["zoido"]
